[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "facebook-scraper>=0.2.59",
    "lxml-html-clean>=0.4.3",
]
